services:
  - type: web
    name: n8n-bot-farsi
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: GENERIC_TIMEZONE
        value: Asia/Tehran
      - key: WEBHOOK_URL
        generateValue: true
    healthCheckPath: /healthz
    autoDeploy: true
